name: communityappboilerplate
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^4.1.2+1
  bordered_text: ^1.0.0
  carousel_slider: ^1.4.1
  speech_to_text: ^2.2.0
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  google_sign_in: ^4.5.1
  url_launcher: ^5.4.5
  flutter_svg: ^0.18.0
  provider:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/gs_launcher.png
    - assets/images/code.png
    - assets/images/github.png
    - assets/images/google.png
    - assets/images/linkedin.png
    - assets/images/flutter1.png
    - assets/images/announcement1.jpg
    - assets/images/announcement2.jpg
    - assets/images/gs.png
    - assets/images/code2.png
    - assets/images/events/event1.jpg
    - assets/images/team/smaranjit_ghose.jpg
    - assets/images/team/anush_bhatia.jpg
    - assets/images/team/ousnik_polley.jpg
    - assets/images/team/saswat_nayak.jpg
    - assets/images/team/sukkrit_sharma.jpg
    - assets/images/team/ambarish_datar.jpg
    - assets/images/team/apoorva_gupta.jpg
    - assets/images/team/arnab_dutta.jpg
    - assets/images/team/bidisha_mukherjea.jpg
    - assets/images/team/jasprit_kaur.jpg
    - assets/images/team/rahul_sarvadevabhatla.jpg
    - assets/images/team/ram_maheshwari.jpg
    - assets/images/team/Rishabh_Verma.jpg
    - assets/images/team/ritik_rajput.jpg
    - assets/images/team/sriyash.jpg
    - assets/images/team/suhrid_datta.jpg
    - assets/images/team/suryanshi_kaushik.jpg
    - assets/images/linkedinblue.png
    - assets/images/githubblack.png
    - assets/images/team.png
    - assets/images/custom.svg
    - assets/images/html.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
